[workspace]
members = ["upgrayedd-macros", "upgrayedd"]
resolver = "2"

[workspace.metadata.release]
publish = false            # handled by GitHub Actions
push = true
shared-version = true
consolidate-commits = true
